config/routes.rb
Blitzen::Application.routes.draw do
  get "home/index"

  devise_for :users

  authenticated :user do
    root to: 'presents#index'
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :presents

end

app/models/present.rb
class Present < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient
  attr_accessible :cost, :delivered, :given, :product, :purchased, :store, :split
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  has_many :presents

  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :presents

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @presents = Present.where(user_id: current_user)
  end

  def new
    @present = Present.new
  end

  def create
    @present = current_user.presents.create!(params[:present])
    respond_to do |format|
      format.html { redirect_to presents_url }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = 'Blitzen'

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; <%= Time.now.year %> Tim Cheadle
  </small>
  <nav>
    <ul>
      <li><%= link_to "About"   %></li>
      <li><%= link_to "Contact" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Blitzen", root_path, class: "brand" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile" %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/presents/_form.html.erb
<%= form_for @present, remote: true do |f| %>
  <%= f.label :product %>
  <%= f.text_field :product %>

  <%= f.submit 'Add Present', class: 'btn' %>
<% end %>

app/views/presents/_present.html.erb
<li><%= present.product %></li>

app/views/presents/create.js.erb
$('#new_present').remove();
$('#new_link').show();
$('#presents').append('<%= j render(@present) %>')

app/views/presents/index.html.erb
<% provide(:title, 'Presents')%>

<ul id="presents">
  <%= render @presents %>
</ul>

<%= link_to 'Add Present', new_present_path, id: 'new_link', remote: true %>

app/views/presents/new.html.erb
<h1>Add Present</h1>

<%= render 'form' %>

<p><%= link_to "Back to presents", presents_path %></p>

app/views/presents/new.js.erb
$('#new_link').hide().after('<%= j render('form') %>');